class=com/android/server/inputmethod/InputMethodManagerService
method=setInputMethodAndSubtypeLocked(Ljava/lang/String;Landroid/view/inputmethod/InputMethodSubtype;Lcom/android/server/inputmethod/UserData;)V
operation=replace-method
expected_matches=1
