class=com/android/server/inputmethod/InputMethodManagerService
method=lambda$getEnabledInputMethodListInternal$8(IILcom/android/server/inputmethod/InputMethodSettings;Landroid/view/inputmethod/InputMethodInfo;)Z
operation=replace-method
expected_matches=1
