class=com/android/server/pm/ScanPackageUtils
method=*
operation=replace-method-result-all
expected_matches=all
anchor=ApkSignatureVerifier;->getMinimumSignatureSchemeVersionForTargetSdk(I)I
return_type=I
value=0
