class=com/android/server/inputmethod/InputMethodSubtypeSwitchingController
method=getNextInputMethodLocked(ZLandroid/view/inputmethod/InputMethodInfo;Landroid/view/inputmethod/InputMethodSubtype;IZ)Lcom/android/server/inputmethod/InputMethodSubtypeSwitchingController$ImeSubtypeListItem;
operation=replace-method
expected_matches=1
