class=com/android/server/inputmethod/InputMethodSubtypeSwitchingController
method=onUserActionLocked(Landroid/view/inputmethod/InputMethodInfo;Landroid/view/inputmethod/InputMethodSubtype;)Z
operation=replace-method
expected_matches=1
