class=com/android/server/inputmethod/InputMethodManagerService
method=$r8$lambda$sKGv-Z06Eo9ws-U6iYbSnLzbUI0(Lcom/android/server/inputmethod/InputMethodManagerService;IILcom/android/server/inputmethod/InputMethodSettings;Landroid/view/inputmethod/InputMethodInfo;)Z
operation=replace-method
expected_matches=1
