/system_ext/priv-app/Settings/Settings.apk|settings-support
/system_ext/framework/miui-framework.jar|framework-support
/system/framework/services.jar|services-enabled-list,services-switch-target,services-filter-capability,services-next-capability,services-user-action
/product/app/MiuiFrequentPhrase/MiuiFrequentPhrase.apk|phrase-attach-color,phrase-layout-color,phrase-enabled-list,phrase-support,phrase-setting-color,phrase-color-helper,phrase-cycle-language,phrase-cycle-ime,phrase-provider-allowlist,phrase-voice-input,phrase-voice-listener
